// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMLbGP2Wl0oxYOqfeBfYgxuNzxPocm7w',
    appId: '1:358544930575:android:e5847557b5eb3dc2a9b07a',
    messagingSenderId: '358544930575',
    projectId: 'legalsupportai',
    storageBucket: 'legalsupportai.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUEQ7mXq6D1q8cDkPwtgb1f7zdo_5iPDM',
    appId: '1:358544930575:web:335196e35710696aa9b07a',
    messagingSenderId: '358544930575',
    projectId: 'legalsupportai',
    authDomain: 'legalsupportai.firebaseapp.com',
    storageBucket: 'legalsupportai.firebasestorage.app',
    measurementId: 'G-J4CCQ9D5C4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLr5apHZ4jYfT7ZxF5CIaEiS20nqA_StU',
    appId: '1:358544930575:ios:f93c1956a3e5840ba9b07a',
    messagingSenderId: '358544930575',
    projectId: 'legalsupportai',
    storageBucket: 'legalsupportai.firebasestorage.app',
    iosBundleId: 'com.example.legalSupportAi',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLr5apHZ4jYfT7ZxF5CIaEiS20nqA_StU',
    appId: '1:358544930575:ios:f93c1956a3e5840ba9b07a',
    messagingSenderId: '358544930575',
    projectId: 'legalsupportai',
    storageBucket: 'legalsupportai.firebasestorage.app',
    iosBundleId: 'com.example.legalSupportAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUEQ7mXq6D1q8cDkPwtgb1f7zdo_5iPDM',
    appId: '1:358544930575:web:6a4b04c517ae7a30a9b07a',
    messagingSenderId: '358544930575',
    projectId: 'legalsupportai',
    authDomain: 'legalsupportai.firebaseapp.com',
    storageBucket: 'legalsupportai.firebasestorage.app',
    measurementId: 'G-YVX9N2BCVZ',
  );
}
